name: Build and deploy Vite app to Azure Web App - OSInventory

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_AZURE_REDIRECT: ${{ secrets.AZURE_REDIRECT }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_349F0716B5514C449DA2EF89D6FC82CB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B6851A7EADE4485958AEAFAC78EE341 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60A442C57C26473E88D7E84F2A2B4D6F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "OSInventory"
          slot-name: "Production"
          package: ./dist
